name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Show 5 most recent commits
        run: git log --oneline -n 5

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@${{ secrets.APP_URL }}/hello-nodejs
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          branch: main
          trace: 1
          git_push_flags: --force
