name: Test with Nodejs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        nodejs-version: [22, 20, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          nodejs-version: ${{ matrix.nodejs-version }}

      - run: node index.js &

      - name: Run the health check validation
        run: while ! curl -s 'http://localhost:3000/health' | grep 'OK'; do sleep 1; done
        timeout-minutes: 3
