name: Test with Deno

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno --version

      - run: deno --unstable-detect-cjs --allow-net --allow-env index.js &

      - name: Run the health check validation
        run: while ! curl -s 'http://localhost:3000/health' | grep 'OK'; do sleep 1; done
        timeout-minutes: 3
